"""Public model catalog, factory preflight, and runtime composition APIs."""

from .catalog import (
    BUILTIN_MODELS,
    MODEL_CATEGORIES,
    MODEL_CATALOG_FORMAT,
    MODEL_CATEGORY_BY_KIND,
    MODEL_KINDS,
    MODEL_KINDS_BY_CATEGORY,
    ModelCatalog,
    ModelCatalogError,
    ModelIntegrationError,
    PreparedFactory,
    ResolvedModel,
    available_models,
    check_declared_assets,
    contract_version_for_kind,
    effective_factory_kwargs,
    instantiate_factory_model,
    instantiate_video_generation_model,
    instantiate_vlm_model,
    load_model_catalog,
    model_category_for_kind,
    prepare_model_factory,
    resolve_model,
)
from .checking import check_model, run_model_smoke
from .runtime import (
    ExternalDepthEstimatorAdapter,
    RUNTIME_MODEL_FORMAT,
    RuntimeComposition,
    compose_runtime_config,
    public_runtime_config,
)

__all__ = [
    "BUILTIN_MODELS",
    "ExternalDepthEstimatorAdapter",
    "MODEL_CATEGORIES",
    "MODEL_CATALOG_FORMAT",
    "MODEL_CATEGORY_BY_KIND",
    "MODEL_KINDS",
    "MODEL_KINDS_BY_CATEGORY",
    "RUNTIME_MODEL_FORMAT",
    "ModelCatalog",
    "ModelCatalogError",
    "ModelIntegrationError",
    "PreparedFactory",
    "ResolvedModel",
    "RuntimeComposition",
    "available_models",
    "check_declared_assets",
    "check_model",
    "compose_runtime_config",
    "contract_version_for_kind",
    "effective_factory_kwargs",
    "instantiate_factory_model",
    "instantiate_video_generation_model",
    "instantiate_vlm_model",
    "load_model_catalog",
    "model_category_for_kind",
    "prepare_model_factory",
    "public_runtime_config",
    "resolve_model",
    "run_model_smoke",
]
